### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BrianV87** [WildCodeSchool/2023-03-remote-fr-php-la-banque-postale#101]
Pourquoi j'ai encore accès au lien de connexion et d'inscription quand je suis connecté ? (voir la redirection ??) 
hover à la poubelle lors des quiz ???
Buton question suivante quand le quiz est fini ? Peut etre l'enlever à la fin du questionnaire. 
Je peux pas partager ma progession ?
Peut etre mettre question reponse sur la même page partie admin ? 
Peut etre mettre dans la barre de recherche un résultat quand on tape quelque chose pour eviter de faire entrer et de chercher désespérément un bon mot clé ?

**Comment by ninaschadel** [comment]
T'as accès à connexion ou ? 
C'est quoi hover a la poubelle exprime toi là !!!
Le bouton suivant n'est pas cliquable à la fin du quiz, et le bouton précédent n'est pas cliquable non plus au début. 
Non pas encore on est occupé à regarder toutes les erreurs de votre site là ! 
Les questions et réponses sont modifiables sur la page admin/ tutorial show
Non tu te débrouilles

**Comment by AlexisIMichelas** [comment]
Tout est ok
