### ISSUE TITLE
Progression avec un nouveau profil

### ISSUE THREAD

**Issue by valphi41** [WildCodeSchool/2023-03-remote-fr-php-la-banque-postale#85]
En créant un nouveau profil j'ai bien ma progression totale à 0% mais j'ai la barre "Utiliser mon téléphone" à 12% et "Securité" à 20% sans avoir fais de tutos 😅 

P.S : Votre page 404 est incroyable !

**Comment by ninaschadel** [comment]
ok je me demande si c'est pas à cause de la session car tu es toujours sur la meme page google (je sais pas si c'est francais mdr je vais me pencher dessus), merciii
