### ISSUE TITLE
Proposition d'inscription alors que je suis inscrit

### ISSUE THREAD

**Issue by valphi41** [WildCodeSchool/2023-03-remote-fr-php-la-banque-postale#86]
En remplissant le premier quizz à la fin j'ai eu le message : " Tu as réussis à créer ton adresse mail ? Alors Clique sur le bouton pour t’inscrire et avoir accès à pleins d’autres tutoriels !" (sur le serveur pas encore tester en local)

**Comment by ninaschadel** [comment]
Tu peux venir dans le groupe pour nous expliquer mieux stp? J'arrive pas à trouver :') dsl

**Comment by Karabuff** [comment]
A une condition !!!
Vous recuperer une chti jusqu'a la fin du projet !
Et on choisit le chti !!!
