### ISSUE TITLE
pas de favicon ?

### ISSUE THREAD

**Issue by Karabuff** [WildCodeSchool/2023-03-remote-fr-php-la-banque-postale#87]
Coucou les gôrs ( désolé je me suis transformé en chti )
Site très propre mais ca manque d'un petit favicon :)

**Comment by ninaschadel** [comment]
Mdrrr t'as ouvert une baraque à frites aussi ? HEEEIN ? 
On a préféré utilisé fontawesome pour les icones, favicon est pareil ? Ou c'est autre chose ?

**Comment by ninaschadel** [comment]
je retire ce que je t'ai écris j'ai compris ce que c'était ! je note mercii
