### ISSUE TITLE
Div qui sort du cadre

### ISSUE THREAD

**Issue by Karabuff** [WildCodeSchool/2023-03-remote-fr-php-la-banque-postale#88]
![image](https://github.com/WildCodeSchool/2023-03-remote-fr-php-la-banque-postale/assets/105162386/f90f97c9-547b-4ed7-93c0-ef2d540cb170)
Juste pour savoir si c'était volontaire que ca sorte du cadre ?
Si c'est un choix artistique je dis rien :p les goûts et les couleurs...

**Comment by ninaschadel** [comment]
T'as d'trop beau euh bons yeux Johann ! Je supprime l'animation de ce pas :D
