### ISSUE TITLE
Div fermante en trop sur la route categorie/NomDeLaCategorie

### ISSUE THREAD

**Issue by fliewight** [WildCodeSchool/2023-03-remote-fr-php-la-banque-postale#92]
W3C -> ligne 120/121

**Comment by ninaschadel** [comment]
sur quelle page ?

**Comment by BlueEel** [comment]
de quoi tu parles ? quel template ?

**Comment by fliewight** [comment]
Ah désolé, j'avais pas vu votre message.
Voici par exemple un lien vers une de votre catégorie en passant par le W3C : https://validator.w3.org/nu/?doc=https%3A%2F%2Fla-ligne-bleue.remote-fr-1.wilders.dev%2Fcategorie%2FLigne-bleue

L'erreur n°3 :

Error: Stray end tag div.
From line 120, column 1; to line 120, column 6
></div></div></main

C'est juste une ligne à supprimer ;)
