### ISSUE TITLE
ckeditor

### ISSUE THREAD

**Issue by BrianV87** [WildCodeSchool/2023-03-remote-fr-php-la-banque-postale#97]
Partie Admin : Balise < p >< /p  > dans le titre quand je crée une nouvelle catégorie ? 
Bug de CKEDITOR ! 
 Mettre un | peut être ?

**Comment by ninaschadel** [comment]
j'ai pas les balises t'es sur le déploiement ? Ou local ? Moi local

**Comment by BrianV87** [comment]
L'équipe technique à constaté l'erreur sur le serveur, bien cordialement. 
https://la-ligne-bleue.remote-fr-1.wilders.dev/categorie/
