### ISSUE TITLE
Suppression quizz

### ISSUE THREAD

**Issue by vravanel** [WildCodeSchool/2023-03-remote-fr-php-la-banque-postale#99]
Quand je supprime un quizz j'ai une erreur 500 sur le serveur et en local j'ai cette erreur : 
![image](https://github.com/WildCodeSchool/2023-03-remote-fr-php-la-banque-postale/assets/102947439/51e8e9c7-852e-4318-a4e3-0dc0f6a92aca)

**Comment by ninaschadel** [comment]
T'es sur tu t'es pas trompé de site ? C'est sur origins digital les erreurs de base
